name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40.1.12
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}